### ISSUE TITLE
Font install failed.

### ISSUE THREAD

**Issue by AaronWharton** [DemonCloud/Aix-Vim#11]
I cloned this project and got the .bdf file. When I install the font I got failure like this:
![default](https://cloud.githubusercontent.com/assets/19624442/23742454/c6b6ad50-04e7-11e7-80d6-e0d52d66f63c.png). BTW, I use Ubuntu16.04 LTS.

**Comment by AaronWharton** [comment]
Sorry to disturb you, it seemed like to be the mistake of my config(root). When I reinstalled the os it was OK. Have a nice day!

**Comment by DemonCloud** [comment]
是这样的。 Ubuntu 的话首先要开启对点阵字体的支持。 然后再安装即可

**Comment by AaronWharton** [comment]
@DemonCloud Thanks. 顺便问一下是不是有几个依赖需要翻墙，中途下载失败一直配置不成功= =

**Comment by DemonCloud** [comment]
@AaronWharton 
我列出一些的一些依赖列表（README.md) 

诸如自动编译 YoucompleteMe  会下载Clang 编译所需要的依赖
还有就是fzf搜索， fzf搜索依赖国内下载不了，不过，如果你用的是mac， 可以通过brew直接安装
https://github.com/junegunn/fzf

貌似我没有看到可以额外的第三方安装方式，翻墙吧

**Comment by AaronWharton** [comment]
@DemonCloud 这样。感谢回复
