### ISSUE TITLE
请教个问题啊

### ISSUE THREAD

**Issue by wangding** [DemonCloud/Aix-Vim#12]
刚开始玩 vim，主要是看了你在知乎 vim 专栏上的文章。
尝试用 Vundle 安装了 vim-syntastic/syntastic 语法检查插件，也全局安装了 jslint 和 jshint。好像语法错误没有提示。
另一个问题，Command-T 插件，呼出文件选项列表后，ctl-s 快捷键好像不能用，快捷键用来把选中的文件水平分隔显示。
https://github.com/wangding/tools/blob/master/.vimrc

能抽空帮忙给看一下吗？我的QQ：408542507，非常感谢 :pray:

**Comment by DemonCloud** [comment]
@wangding 
let g:syntastic_javascript_checkers = ['jshint']

jslint 和 jshint 只需要选择其中一种即可。
jshint是通过npm来安装的，也就是说你的电脑需要先安装好nodejs， 控制台中安装指令是
npm install -g jshint （ 等于安装在全局 ）

Ctrl-s 键位不能用可能说明了 是原生键位（也就是说你没有定义使它成为command-T的快捷键）
或者是被其它插件，或者原生键位给占用了.
建议详细看下 command-T的文档.
:help command-t
https://github.com/wincent/command-t/blob/master/doc/command-t.txt

键位设置说明
https://github.com/wincent/command-t/blob/master/doc/command-t.txt#L616

**Comment by wangding** [comment]
非常感谢您的回复。
问题还是没有解决。不知您是否有空，能通过QQ远程协助一下啊？

**Comment by wangding** [comment]
非常感谢您的回复。
syntastic 貌似起作用了，我犯了低级错误，我把代码改错之后，没有保存，在网上看了一下老外的视频，发现保存之后才会报错。
其他的我再查查资料。
