### ISSUE TITLE
windows  windows 版本打开提醒这个？这个是还需要配置python 环境吗？

### ISSUE THREAD

**Issue by tonnyone** [DemonCloud/Aix-Vim#2]
UltiSnips requires py >= 2.7 or any py3 ， 我机器上有python 2.7的环境 ,并且也加到了环境变量里面了

**Comment by DemonCloud** [comment]
@tonnyone 
你在官方下载的 Vim7.4 版本编译的时候有问题.
建议你看下 Markdown 里面说明, 有链接地址 完整的 Vim7.4 支持(Lua 和 Python)编译好的exe可执行程序(_Vim.exe)

地址:

[YVIM + YoucompleteMe](http://pan.baidu.com/s/1bnhOUf1)
[YVIM + Neocomplete](http://pan.baidu.com/s/1o67QYmA)

**Comment by tonnyone** [comment]
我是从你网盘完整下载的,我的python 环境是64位的，是不是需要用32位的python环境?

**Comment by DemonCloud** [comment]
@tonnyone 

Vim 的机制是这样的, 你用是的 32位的Vim 那么就要用 32位的环境, 比如 Python x86
一般来说大部分插件都是32位的, 所以推荐是使用 32位的 Vim

**Comment by tonnyone** [comment]
@DemonCloud 
嗯，好了，谢谢！
