### ISSUE TITLE
number 5 looks the same as 'S'

### ISSUE THREAD

**Issue by iamchaoge** [DemonCloud/Aix-Vim#6]
![image](https://cloud.githubusercontent.com/assets/10483361/15603999/746c6668-2430-11e6-8af2-b722299f2c61.png)

**Comment by DemonCloud** [comment]
木有办法，字体就是这么设计的，其实你可以考虑换个字体，，，么么哒%

**Comment by iamchaoge** [comment]
= = 有强迫症。。我用font-forge试了下发现可以编辑你的bdf文件，但是xterm用bdf字体的话好像大小有限制，超过14px就不变大了，但是转ttf老是失败。。你可以转ttf吗  么么哒

**Comment by DemonCloud** [comment]
bdf 貌似 没法转成 ttf

**Comment by be5invis** [comment]
@DemonCloud 能的，转成曲线——长得像点阵的曲线字体
