### ISSUE TITLE
关于win下的lua问题：

### ISSUE THREAD

**Issue by sunshe35** [DemonCloud/Aix-Vim#7]
https://www.zhihu.com/question/29333426
参考这个帖子的ashfinal回答，他的意思好像是只需要下载那个.dll文件放在与gvim.exe同目录的文件夹下就可以了，不需要手动高lua配置。我是个新手，不知道是不是这个意思，如果是这个意思的话你可以整合进去。

**Comment by DemonCloud** [comment]
首先要明白， windows下没有一个真正的gcc工具给你， Lua 是脚本语言依赖解析引擎所以需要有 gcc的支持， 光一个dll是跑不起来的，所以MinGW还是要装， 你发的这个地址， 答主依云的是告诉你， 有Lua库不够还需要 Vim 在编译的时候， 编译支持Lua才行

**Comment by sunshe35** [comment]
谢谢老大回答，这个问题我是通过编译解决的（编程小白搞这些真的是太难为人了），windows下的vim真的是太麻烦了，各种不爽，学习vim才能体会到linux的各种好处。。。

我编译的时候选择同时支持Python+lua，然后把lua的库放在gvim的同目录下。那么，是不是只有编译的时候需要lua+MinGW，编译成功后他们就不需要了（包括环境变量%luadir%），此时只要gvim的:version显示lua+，然后gvim同目录下又有对应的lua库就行了？编程小白悉心求教。
