### ISSUE TITLE
win 下的问题 the python's site module 不能载入以及 UltiSnips#TrackChange

### ISSUE THREAD

**Issue by sunshe35** [DemonCloud/Aix-Vim#8]
详情：
Error detected while processing function UltiSnips#TrackChange:
E887:Sorry,this command is disabled, the Python's site module could not be load.

新手，不知道该如何解决这个问题，那个lua我配置好了。

**Comment by DemonCloud** [comment]
window下有没有安装python？ 没有的话需要安装一下python， python2 和 python3 都可以

**Comment by sunshe35** [comment]
谢谢老大耐心回复：这个原因好像是python2与Python3产生冲突。

我的电脑上两个版本都装了，但是老大的gvim默认是：:echo has("python") 为 1 :echo has('python3') 为0
意思是只支持Python2的。但是这时候Python3的模块库会与Python2冲突，所以当我们
:py import sys; print(sys.version)
才会产生这个问题： the Python's site module could not be load.

解决方法：
1、更改Python3的安装文件夹名字，如把C:\Python33改成C:\Python33_2，这样就Python3的模块就不会打扰Python2了
2、重新编译，使他只支持Python3
由于我个人只用Python3，所以选择了重新编译这条路。
