### ISSUE TITLE
necomeplete requires Vim 7.3.885 or later with Lua support ("+Lua")问题

### ISSUE THREAD

**Issue by zg55** [DemonCloud/Aix-Vim#9]
按照您写的文档，我将Lua放到和Aix-Vim一个文件夹，然后配置了系统环境变量。再编写文档时gVim下边会出现题目的内容。我以为是我没有下载minGW，于是我便下载了一个[MinGW](https://sourceforge.net/projects/mingw/files/)后来还是没效果，我是不是需要在里边下载g++和Gcc的支持包啊，我只想用Gvim写一些C代码不知道插件对我有没有帮助。

**Comment by DemonCloud** [comment]
MinGW 需要安装之后通过MinGW安装 gcc 和 g++，你装了没有

**Comment by zg55** [comment]
我通过MinGW安装了gcc和g++而且在cmd中输入gcc -v有版本信息，Lua是不是需要Mingw来运行啊，还有5.2和5.3的版本和我下载的Vim（就是您在readme中给的地址）哪个可以兼容，是版本的问题吗？最近刚刚学习vim发现很强大，想学习学习，可是最下边一直出现题目那句话,让我很是头疼。问一下您上传的版本下载后运行：vundleinstall后是不是已经包含了大部分插件？

**Comment by DemonCloud** [comment]
5.2 和 5.3 都可以，Lua最好放在c盘，把环境变量指向C盘，  第一次进Vim的时候， 用:vundleinstall 安装所有插件， .aix 文件夹中 .aix.plug.conf 有插件的列表，不想要的直接禁用掉就行。
